"""new blogviewtoday

Revision ID: 03899f419ccb
Revises: 36172af7f3ac
Create Date: 2017-11-18 12:23:30.264797

"""

# revision identifiers, used by Alembic.
revision = '03899f419ccb'
down_revision = '36172af7f3ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_view_today', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_column('blog_view_today', 'timestamp_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_view_today', sa.Column('timestamp_str', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('blog_view_today', 'count')
    # ### end Alembic commands ###
