"""add about_me and location

Revision ID: 1687295d63fd
Revises: 8447c1827a74
Create Date: 2017-11-08 20:21:07.688094

"""

# revision identifiers, used by Alembic.
revision = '1687295d63fd'
down_revision = '8447c1827a74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
