"""add blogviewtoday

Revision ID: 36172af7f3ac
Revises: 4cbfaab2b19f
Create Date: 2017-11-18 00:52:27.475330

"""

# revision identifiers, used by Alembic.
revision = '36172af7f3ac'
down_revision = '4cbfaab2b19f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
