"""add blogviewtoday

Revision ID: 4cbfaab2b19f
Revises: b4893dd631cc
Create Date: 2017-11-18 00:42:43.359504

"""

# revision identifiers, used by Alembic.
revision = '4cbfaab2b19f'
down_revision = 'b4893dd631cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_view_today',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('timestamp_str', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_view_today_timestamp'), 'blog_view_today', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_view_today_timestamp'), table_name='blog_view_today')
    op.drop_table('blog_view_today')
    # ### end Alembic commands ###
