"""add body_html

Revision ID: 4f420d20d674
Revises: e6fc804be22a
Create Date: 2017-11-08 21:43:58.056630

"""

# revision identifiers, used by Alembic.
revision = '4f420d20d674'
down_revision = 'e6fc804be22a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
