"""add confirmed in users

Revision ID: 5133948691fe
Revises: fc7935ef50c9
Create Date: 2017-11-04 16:14:31.579010

"""

# revision identifiers, used by Alembic.
revision = '5133948691fe'
down_revision = 'fc7935ef50c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
