"""fix first() bug

Revision ID: 645607464b78
Revises: 869f9add7f5f
Create Date: 2017-12-12 22:28:25.323646

"""

# revision identifiers, used by Alembic.
revision = '645607464b78'
down_revision = '869f9add7f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
