"""add open_flag in posts

Revision ID: 8092b231e956
Revises: 03899f419ccb
Create Date: 2017-11-20 22:01:19.095878

"""

# revision identifiers, used by Alembic.
revision = '8092b231e956'
down_revision = '03899f419ccb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('open_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'open_flag')
    # ### end Alembic commands ###
