"""post to post_id in comment

Revision ID: 869f9add7f5f
Revises: 76b3748d22fa
Create Date: 2017-12-12 22:25:38.601449

"""

# revision identifiers, used by Alembic.
revision = '869f9add7f5f'
down_revision = '76b3748d22fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
