"""update comment with content_html

Revision ID: 8a4230eb8ce5
Revises: 645607464b78
Create Date: 2017-12-13 21:12:01.893399

"""

# revision identifiers, used by Alembic.
revision = '8a4230eb8ce5'
down_revision = '645607464b78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('open_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'open_flag')
    op.drop_column('comments', 'content_html')
    # ### end Alembic commands ###
