"""add blogview without timestamp

Revision ID: b4893dd631cc
Revises: 8553a96593c0
Create Date: 2017-11-18 00:15:21.615630

"""

# revision identifiers, used by Alembic.
revision = 'b4893dd631cc'
down_revision = '8553a96593c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_view_timestamp', table_name='blog_view')
    op.drop_column('blog_view', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_view', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_blog_view_timestamp', 'blog_view', ['timestamp'], unique=False)
    # ### end Alembic commands ###
