"""add name

Revision ID: e6fc804be22a
Revises: 1687295d63fd
Create Date: 2017-11-08 20:27:19.094029

"""

# revision identifiers, used by Alembic.
revision = 'e6fc804be22a'
down_revision = '1687295d63fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
